apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx-applicationset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/neerajsinghnegi/argocd.git
        revision: HEAD
        directories:
          - path: app*
  template:
    metadata:
      name: '{{path}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/neerajsinghnegi/argocd.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated: {}